version: '3.8'

services:
  db:
    image: postgres:16.1
    ports:
      - "5432:5432"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '256M'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=develop
