### Server requests
###
GET http://5.42.220.6:3000/api/placements/

### Placements
###
GET http://localhost:3000/api/placements/

###
GET http://localhost:3000/api/placements/309

###
POST http://localhost:3000/api/placements/store
Content-Type: application/json

{
    "room_id": 218,
    "number_of_seats": 30,
    "available_seats": 30
}

### participants
###
GET http://localhost:3000/api/participants/

###
GET http://localhost:3000/api/participants/2

###
POST http://localhost:3000/api/participants/store
Content-Type: application/json

{
    "surname": "Мариева",
    "firstname": "Мария",
    "patronymic": "Амеговная",
    "gender": "Женский",
    "birthdate": "2002-11-11",
    "age": 18,
    "phone": "+79273408180",
    "email": "beautygirl@gmail.com",
    "school": "Лицей №12",
    "address": "Саранск",
    "classroom": 11,
    "subject": "Химия",
    "citizenship": "Россия",
    "passport_series": 1234,
    "passport_number": 123456
}


### organizers
###
GET http://localhost:3000/api/organizers/

###
GET http://localhost:3000/api/organizers/Evangelion@gmail.com&iloveasuka

###
POST http://localhost:3000/api/organizers/store
Content-Type: application/json

{
    "surname": "Отакус",
    "firstname": "Виб",
    "patronymic": "Лович",
    "faculty": "ФМИиТ",
    "student_group": 303,
    "email": "Evangelion@gmail.com",
    "password": "iloveasuka"

}

### logs
###
GET http://localhost:3000/api/logging/

###
GET http://localhost:3000/api/logging/2

###
POST http://localhost:3000/api/logging/store
Content-Type: application/json

{
    "log_message": "Организатор не смог внести участника в базу данных. Причина: Все комнаты заполнены"
}