###
POST http://localhost:3000/api/placements/store
Content-Type: application/json

{
    "room_id": 218,
    "number_of_seats": 30,
    "available_seats": 30
}

###
GET  http://localhost:3000/api/placements/

###
GET http://localhost:3000/api/placements/309
